version: "3.8"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: student@123
      MYSQL_DATABASE: authdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: student@123
      DB_NAME: authdb
      JWT_SECRET_KEY: super-secret-key
    ports:
      - "5000:5000"

volumes:
  mysql_data:
